// <auto-generated />
using System;
using CompanyMicroservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyMicroservice.Migrations
{
    [DbContext(typeof(StockMarketContext))]
    [Migration("20220223155229_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompanyMicroservice.Model.CompanyDetail", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyCeo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("CompanyCEO");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StockExchange")
                        .HasColumnType("int");

                    b.Property<decimal>("Turnover")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CompanyId", "CompanyCode")
                        .HasName("PK_CompanyId");

                    b.HasIndex("StockExchange");

                    b.ToTable("CompanyDetails");
                });

            modelBuilder.Entity("CompanyMicroservice.Model.StockExchange", b =>
                {
                    b.Property<int>("ExchangeId")
                        .HasColumnType("int")
                        .HasColumnName("ExchangeID");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ExchangeId")
                        .HasName("PK_ExchangeId");

                    b.ToTable("StockExchange");
                });

            modelBuilder.Entity("CompanyMicroservice.Model.CompanyDetail", b =>
                {
                    b.HasOne("CompanyMicroservice.Model.StockExchange", "StockExchangeNavigation")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("StockExchange")
                        .HasConstraintName("Fk_StockExchange_ExchangeID");

                    b.Navigation("StockExchangeNavigation");
                });

            modelBuilder.Entity("CompanyMicroservice.Model.StockExchange", b =>
                {
                    b.Navigation("CompanyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
